//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitoDemoEka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoitopaikka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoitopaikka()
        {
            this.Toimipiste1 = new HashSet<Toimipiste>();
            this.Varaus1 = new HashSet<Varaus>();
        }
    
        public int Hoitopaikka_id { get; set; }
        public string Hoitopaikan_Nimi { get; set; }
        public string Hoitopaikan_Numero { get; set; }
        public Nullable<int> Toimipiste_id { get; set; }
        public Nullable<int> Varaus_id { get; set; }
    
        public virtual Toimipiste Toimipiste { get; set; }
        public virtual Varaus Varaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toimipiste> Toimipiste1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Varaus> Varaus1 { get; set; }
    }
}
