//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitoDemoEka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kauppeedbEntities : DbContext
    {
        public kauppeedbEntities()
            : base("name=kauppeedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakas> Asiakas { get; set; }
        public virtual DbSet<Henkilokunta> Henkilokunta { get; set; }
        public virtual DbSet<Hoitaja> Hoitaja { get; set; }
        public virtual DbSet<Hoitopaikka> Hoitopaikka { get; set; }
        public virtual DbSet<Kayttaja> Kayttaja { get; set; }
        public virtual DbSet<Osoite> Osoite { get; set; }
        public virtual DbSet<Palvelu> Palvelu { get; set; }
        public virtual DbSet<Puhelin> Puhelin { get; set; }
        public virtual DbSet<Toimipiste> Toimipiste { get; set; }
        public virtual DbSet<Varaus> Varaus { get; set; }
        public virtual DbSet<Rooli> Rooli { get; set; }
    }
}
