//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitoDemoEka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puhelin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puhelin()
        {
            this.Asiakas = new HashSet<Asiakas>();
            this.Henkilokunta = new HashSet<Henkilokunta>();
            this.Hoitaja = new HashSet<Hoitaja>();
            this.Toimipiste1 = new HashSet<Toimipiste>();
        }
    
        public int Puhelin_id { get; set; }
        public string Puhelinnumero_1 { get; set; }
        public string Puhelinnumero_2 { get; set; }
        public string Puhelinnumero_3 { get; set; }
        public Nullable<int> Asiakas_id { get; set; }
        public Nullable<int> Hoitaja_id { get; set; }
        public Nullable<int> Henkilokunta_id { get; set; }
        public Nullable<int> Toimipiste_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakas> Asiakas { get; set; }
        public virtual Asiakas Asiakas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Henkilokunta> Henkilokunta { get; set; }
        public virtual Henkilokunta Henkilokunta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitaja> Hoitaja { get; set; }
        public virtual Hoitaja Hoitaja1 { get; set; }
        public virtual Toimipiste Toimipiste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toimipiste> Toimipiste1 { get; set; }
    }
}
