//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitoDemoEka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toimipiste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toimipiste()
        {
            this.Hoitopaikka = new HashSet<Hoitopaikka>();
            this.Osoite = new HashSet<Osoite>();
            this.Palvelu = new HashSet<Palvelu>();
            this.Puhelin = new HashSet<Puhelin>();
            this.Varaus = new HashSet<Varaus>();
        }
    
        public int Toimipiste_id { get; set; }
        public string Toimipiste_Nimi { get; set; }
        public string Huomio { get; set; }
        public Nullable<int> Hoitopaikka_id { get; set; }
        public Nullable<int> Osoite_id { get; set; }
        public Nullable<int> Puhelin_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitopaikka> Hoitopaikka { get; set; }
        public virtual Hoitopaikka Hoitopaikka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osoite> Osoite { get; set; }
        public virtual Osoite Osoite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palvelu> Palvelu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puhelin> Puhelin { get; set; }
        public virtual Puhelin Puhelin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Varaus> Varaus { get; set; }
    }
}
